version: '3.1'

services:
  web:
    container_name: apache
    image: projekt
    ports:
      - "80:80"
    volumes:
      - "./www:/var/www/site"

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"