version: '3.1'

services:
  web:
    container_name: apache
    image: projekt
    ports:
      - "80:80"
    volumes:
      - "./www:/var/www/site"

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: haslohaslo123
    ports:
      - "3307:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db-vol:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"

volumes:
  db-vol: