version: '3.1'

services:
  web:
    container_name: apache
    image: apache_php
    restart: always
    environment:
      - PHP_IDE_CONFIG=serverName=localhost.test
    ports:
      - "80:80"
    volumes:
      - "./code:/var/www/code"

  db:
    container_name: mariadb
    image: mariadb:10.5.15
    command: mysqld --sql_mode=NO_ENGINE_SUBSTITUTION --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: haslohaslo123
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mariadb
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"

volumes:
  db-vol:
  db:
    driver: local